//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FileManager.Resources.Settings {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "17.4.0.0")]
    internal sealed partial class Presets : global::System.Configuration.ApplicationSettingsBase {
        
        private static Presets defaultInstance = ((Presets)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Presets())));
        
        public static Presets Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool SearchOptions {
            get {
                return ((bool)(this["SearchOptions"]));
            }
            set {
                this["SearchOptions"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool SearchOptionsPath {
            get {
                return ((bool)(this["SearchOptionsPath"]));
            }
            set {
                this["SearchOptionsPath"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool SearchOptionsSearchInput {
            get {
                return ((bool)(this["SearchOptionsSearchInput"]));
            }
            set {
                this["SearchOptionsSearchInput"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool SearchOptionsSubdirectory {
            get {
                return ((bool)(this["SearchOptionsSubdirectory"]));
            }
            set {
                this["SearchOptionsSubdirectory"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool SearchOptionsCaseSensitive {
            get {
                return ((bool)(this["SearchOptionsCaseSensitive"]));
            }
            set {
                this["SearchOptionsCaseSensitive"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool SearchOptionsFileName {
            get {
                return ((bool)(this["SearchOptionsFileName"]));
            }
            set {
                this["SearchOptionsFileName"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool SearchOptionsFileContent {
            get {
                return ((bool)(this["SearchOptionsFileContent"]));
            }
            set {
                this["SearchOptionsFileContent"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool General {
            get {
                return ((bool)(this["General"]));
            }
            set {
                this["General"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool GeneralCardCollapse {
            get {
                return ((bool)(this["GeneralCardCollapse"]));
            }
            set {
                this["GeneralCardCollapse"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool GeneralCardCollapseMove {
            get {
                return ((bool)(this["GeneralCardCollapseMove"]));
            }
            set {
                this["GeneralCardCollapseMove"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool GeneralCardCollapseDelete {
            get {
                return ((bool)(this["GeneralCardCollapseDelete"]));
            }
            set {
                this["GeneralCardCollapseDelete"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool GeneralCardCollapseRename {
            get {
                return ((bool)(this["GeneralCardCollapseRename"]));
            }
            set {
                this["GeneralCardCollapseRename"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool GeneralMove {
            get {
                return ((bool)(this["GeneralMove"]));
            }
            set {
                this["GeneralMove"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool GeneralMoveSubdirectoryNameInput {
            get {
                return ((bool)(this["GeneralMoveSubdirectoryNameInput"]));
            }
            set {
                this["GeneralMoveSubdirectoryNameInput"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool GeneralMoveNameOfFileOrCountUps {
            get {
                return ((bool)(this["GeneralMoveNameOfFileOrCountUps"]));
            }
            set {
                this["GeneralMoveNameOfFileOrCountUps"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool GeneralRename {
            get {
                return ((bool)(this["GeneralRename"]));
            }
            set {
                this["GeneralRename"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool GeneralRenameReplaceFrom {
            get {
                return ((bool)(this["GeneralRenameReplaceFrom"]));
            }
            set {
                this["GeneralRenameReplaceFrom"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool GeneralRenameReplaceTo {
            get {
                return ((bool)(this["GeneralRenameReplaceTo"]));
            }
            set {
                this["GeneralRenameReplaceTo"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool GeneralRenameReplaceStartIndex {
            get {
                return ((bool)(this["GeneralRenameReplaceStartIndex"]));
            }
            set {
                this["GeneralRenameReplaceStartIndex"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool GeneralRenameReplaceLength {
            get {
                return ((bool)(this["GeneralRenameReplaceLength"]));
            }
            set {
                this["GeneralRenameReplaceLength"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool GeneralRenameReplaceIndexOrString {
            get {
                return ((bool)(this["GeneralRenameReplaceIndexOrString"]));
            }
            set {
                this["GeneralRenameReplaceIndexOrString"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool GeneralRenameSwapInput {
            get {
                return ((bool)(this["GeneralRenameSwapInput"]));
            }
            set {
                this["GeneralRenameSwapInput"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool GeneralRenameSwapPartOne {
            get {
                return ((bool)(this["GeneralRenameSwapPartOne"]));
            }
            set {
                this["GeneralRenameSwapPartOne"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool GeneralRenameSwapPartTwo {
            get {
                return ((bool)(this["GeneralRenameSwapPartTwo"]));
            }
            set {
                this["GeneralRenameSwapPartTwo"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool GeneralRenameInsertInput {
            get {
                return ((bool)(this["GeneralRenameInsertInput"]));
            }
            set {
                this["GeneralRenameInsertInput"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool GeneralRenameInsertCountUp {
            get {
                return ((bool)(this["GeneralRenameInsertCountUp"]));
            }
            set {
                this["GeneralRenameInsertCountUp"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool SavePresets {
            get {
                return ((bool)(this["SavePresets"]));
            }
            set {
                this["SavePresets"] = value;
            }
        }
    }
}
