using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace FileManager.Resources
{
    static class ExifToolSupportedFiles
    {
        public static IReadOnlyDictionary<string, string> Readable { get; } = new Dictionary<string, string>
        {
            { "360", "GoPro 360 video (QuickTime-based)" },
            { "3FR", "Hasselblad RAW (TIFF-based)" },
            { "3G2", "3rd Gen. Partnership Project 2 a/v (QuickTime-based)" },
            { "3GP2", "3rd Gen. Partnership Project 2 a/v (QuickTime-based)" },
            { "3GP", "3rd Gen. Partnership Project a/v (QuickTime-based)" },
            { "3GPP", "3rd Gen. Partnership Project a/v (QuickTime-based)" },
            { "A", "Unix static library code Archive" },
            { "AA", "Audible Audiobook" },
            { "AAE", "Apple edit information (XML PLIST-based)" },
            { "AAX", "Audible Enhanced Audiobook (QuickTime-based)" },
            { "ACR", "American College of Radiology ACR-NEMA (DICOM-like)" },
            { "AFM", "Adobe [Composite/Multiple Master] Font Metrics" },
            { "ACFM", "Adobe [Composite/Multiple Master] Font Metrics" },
            { "AMFM", "Adobe [Composite/Multiple Master] Font Metrics" },
            { "AI", "Adobe Illustrator [Template] (PS or PDF)" },
            { "AIT", "Adobe Illustrator [Template] (PS or PDF)" },
            { "AIFF", "Audio Interchange File Format [Compressed]" },
            { "AIF", "Audio Interchange File Format [Compressed]" },
            { "AIFC", "Audio Interchange File Format [Compressed]" },
            { "APE", "Monkey's Audio" },
            { "ARQ", "Sony Alpha Pixel-Shift RAW (TIFF-based)" },
            { "ARW", "Sony Alpha RAW (TIFF-based)" },
            { "ASF", "Microsoft Advanced Systems Format" },
            { "AVI", "Audio Video Interleaved (RIFF-based)" },
            { "AVIF", "AV1 Image File Format (QuickTime-based)" },
            { "BMP", "Windows BitMaP / Device Independent Bitmap" },
            { "DIB", "Windows BitMaP / Device Independent Bitmap" },
            { "BPG", "Better Portable Graphics" },
            { "BTF", "BigTIFF (64-bit Tagged Image File Format)" },
            { "CHM", "Microsoft Compiled HTML format" },
            { "COS", "Capture One Settings (XML-based)" },
            { "CR2", "Canon RAW 2 (TIFF-based) (CR2 spec)" },
            { "CR3", "Canon RAW 3 (QuickTime-based) (CR3 spec)" },
            { "CRM", "Canon RAW Movie (QuickTime-based)" },
            { "CRW", "Canon RAW Camera Image File Format (CRW spec)" },
            { "CIFF", "Canon RAW Camera Image File Format (CRW spec)" },
            { "CS1", "Sinar CaptureShop 1-shot RAW (PSD-based)" },
            { "CSV", "Comma-Separated Values" },
            { "CZI", "Zeiss Integrated Software RAW (ZISRAW)" },
            { "DCM", "DICOM - Digital Imaging and Communications in Medicine" },
            { "DC3", "DICOM - Digital Imaging and Communications in Medicine" },
            { "DIC", "DICOM - Digital Imaging and Communications in Medicine" },
            { "DICM", "DICOM - Digital Imaging and Communications in Medicine" },
            { "DCP", "DNG Camera Profile (DNG-like)" },
            { "DCR", "Kodak Digital Camera RAW (TIFF-based)" },
            { "DFONT", "Macintosh Data Fork Font" },
            { "DIVX", "DivX media format (ASF-based)" },
            { "DJVU", "DjVu image (AIFF-like)" },
            { "DJV", "DjVu image (AIFF-like)" },
            { "DNG", "Digital Negative (TIFF-based)" },
            { "DOC", "Microsoft Word Document/Template (FPX-like)" },
            { "DOT", "Microsoft Word Document/Template (FPX-like)" },
            { "DOCX", "Office Open XML Document [Macro-enabled]" },
            { "DOCM", "Office Open XML Document [Macro-enabled]" },
            { "DOTX", "Office Open XML Document Template [Macro-enabled]" },
            { "DOTM", "Office Open XML Document Template [Macro-enabled]" },
            { "DPX", "Digital Picture Exchange" },
            { "DR4", "Canon DPP version 4 Recipe" },
            { "DSS", "Digital Speech Standard [2]" },
            { "DS2", "Digital Speech Standard [2]" },
            { "DYLIB", "MacOS Mach-O executable and library files" },
            { "DV", "Digital Video" },
            { "DVB", "Digital Video Broadcasting (QuickTime-based)" },
            { "DVR-MS", "Microsoft Digital Video Recording (ASF-based)" },
            { "EIP", "Capture One Enhanced Image Package (ZIP-based)" },
            { "EPS", "[Encapsulated] PostScript Format" },
            { "EPSF", "[Encapsulated] PostScript Format" },
            { "PS", "[Encapsulated] PostScript Format" },
            { "EPUB", "Electronic Publication (ZIP/XML-based)" },
            { "ERF", "Epson RAW Format (TIFF-based)" },
            { "EXE", "DOS/Windows executable and library files" },
            { "DLL", "DOS/Windows executable and library files" },
            { "EXIF", "Exchangeable Image File Format metadata (TIFF-based)" },
            { "EXR", "Open EXR (Extended Range)" },
            { "EXV", "Exiv2 metadata file (JPEG-based)" },
            { "F4A", "Adobe Flash Player 9+ Audio/Video (QuickTime-based)" },
            { "F4B", "Adobe Flash Player 9+ Audio/Video (QuickTime-based)" },
            { "F4P", "Adobe Flash Player 9+ Audio/Video (QuickTime-based)" },
            { "F4V", "Adobe Flash Player 9+ Audio/Video (QuickTime-based)" },
            { "FFF", "Hasselblad Flexible File Format (TIFF-based)" },
            { "FITS", "Flexible Image Transport System" },
            { "FLA", "Macromedia/Adobe Flash project (FPX-like)" },
            { "FLAC", "Free Lossless Audio Codec" },
            { "FLIF", "Free Lossless Image Format" },
            { "FLV", "Flash Video" },
            { "FPF", "FLIR Public image Format" },
            { "FPX", "FlashPix image" },
            { "GIF", "Compuserve Graphics Interchange Format" },
            { "GPR", "GoPro RAW (DNG-based)" },
            { "GZ", "GNU ZIP compressed archive" },
            { "GZIP", "GNU ZIP compressed archive" },
            { "HDP", "Windows HD Photo / Media Photo / JPEG XR (TIFF-based)" },
            { "WDP", "Windows HD Photo / Media Photo / JPEG XR (TIFF-based)" },
            { "JXR", "Windows HD Photo / Media Photo / JPEG XR (TIFF-based)" },
            { "HDR", "Radiance RGBE High Dynamic-Range" },
            { "HEIC", "High Efficiency Image Format (QuickTime-based)" },
            { "HEIF", "High Efficiency Image Format (QuickTime-based)" },
            { "HIF", "High Efficiency Image Format (QuickTime-based)" },
            { "HTML", "[Extensible] HyperText Markup Language" },
            { "HTM", "[Extensible] HyperText Markup Language" },
            { "XHTML", "[Extensible] HyperText Markup Language" },
            { "ICC", "International Color Consortium color profile" },
            { "ICM", "International Color Consortium color profile" },
            { "ICS", "iCalendar Schedule" },
            { "ICAL", "iCalendar Schedule" },
            { "IDML", "Adobe InDesign Markup Language (ZIP/XML-based)" },
            { "IIQ", "Phase One Intelligent Image Quality RAW (TIFF-based)" },
            { "IND", "Adobe InDesign Document/Template" },
            { "INDD", "Adobe InDesign Document/Template" },
            { "INDT", "Adobe InDesign Document/Template" },
            { "INSP", "Insta360 Picture (JPEG-based)" },
            { "INSV", "Insta360 Video (QuickTime-based)" },
            { "INX", "Adobe InDesign Interchange (XML-based)" },
            { "ISO", "ISO 9660 disk image" },
            { "ITC", "iTunes Cover Flow artwork" },
            { "J2C", "JPEG 2000 codestream" },
            { "J2K", "JPEG 2000 codestream" },
            { "JPC", "JPEG 2000 codestream" },
            { "JP2", "JPEG 2000 image [Compound/Extended]" },
            { "JPF", "JPEG 2000 image [Compound/Extended]" },
            { "JPM", "JPEG 2000 image [Compound/Extended]" },
            { "JPX", "JPEG 2000 image [Compound/Extended]" },
            { "JPEG", "Joint Photographic Experts Group image" },
            { "JPG", "Joint Photographic Experts Group image" },
            { "JPE", "Joint Photographic Experts Group image" },
            { "JSON", "JavaScript Object Notation" },
            { "JXL", "JPEG XL (codestream and ISO BMFF)" },
            { "K25", "Kodak DC25 RAW (TIFF-based)" },
            { "KDC", "Kodak Digital Camera RAW (TIFF-based)" },
            { "KEY", "Apple iWork '09 Keynote presentation/Theme" },
            { "KTH", "Apple iWork '09 Keynote presentation/Theme" },
            { "LA", "Lossless Audio (RIFF-based)" },
            { "LFP", "Lytro Light Field Picture" },
            { "LFR", "Lytro Light Field Picture" },
            { "LIF", "Leica Image File" },
            { "LNK", "Microsoft Shell Link (Windows shortcut)" },
            { "LRV", "Low-Resolution Video (QuickTime-based)" },
            { "M2TS", "MPEG-2 Transport Stream (used for AVCHD video)" },
            { "MTS", "MPEG-2 Transport Stream (used for AVCHD video)" },
            { "M2T", "MPEG-2 Transport Stream (used for AVCHD video)" },
            { "TS", "MPEG-2 Transport Stream (used for AVCHD video)" },
            { "M4A", "MPEG-4 Audio/Video (QuickTime-based)" },
            { "M4B", "MPEG-4 Audio/Video (QuickTime-based)" },
            { "M4P", "MPEG-4 Audio/Video (QuickTime-based)" },
            { "M4V", "MPEG-4 Audio/Video (QuickTime-based)" },
            { "MACOS", "MacOS '._' sidecar file (may have any extension)" },
            { "MAX", "3D Studio MAX (FPX-like)" },
            { "MEF", "Mamiya (RAW) Electronic Format (TIFF-based)" },
            { "MIE", "Meta Information Encapsulation (MIE specification)" },
            { "MIFF", "Magick Image File Format" },
            { "MIF", "Magick Image File Format" },
            { "MKA", "Matroska Audio/Video/Subtitle" },
            { "MKV", "Matroska Audio/Video/Subtitle" },
            { "MKS", "Matroska Audio/Video/Subtitle" },
            { "MOBI", "Mobipocket electronic book (Palm-based)" },
            { "AZW", "Mobipocket electronic book (Palm-based)" },
            { "AZW3", "Mobipocket electronic book (Palm-based)" },
            { "MODD", "Sony Picture Motion metadata (XML PLIST-based)" },
            { "MOI", "MOD Information file" },
            { "MOS", "Creo Leaf Mosaic (TIFF-based)" },
            { "MOV", "Apple QuickTime Movie" },
            { "QT", "Apple QuickTime Movie" },
            { "MP3", "MPEG-1 layer 3 audio" },
            { "MP4", "Motion Picture Experts Group version 4 (QuickTime-based)" },
            { "MPC", "Musepack Audio" },
            { "MPEG", "Motion Picture Experts Group version 1 or 2" },
            { "MPG", "Motion Picture Experts Group version 1 or 2" },
            { "M2V", "Motion Picture Experts Group version 1 or 2" },
            { "MPO", "Extended Multi-Picture format (JPEG with MPF extensions)" },
            { "MQV", "Sony Mobile QuickTime Video" },
            { "MRW", "Minolta RAW" },
            { "MRC", "Medical Research Council" },
            { "MXF", "Material Exchange Format" },
            { "NEF", "Nikon (RAW) Electronic Format (TIFF-based)" },
            { "NKSC", "Nikon Sidecar (XMP-based)" },
            { "NMBTEMPLATE", "Apple iWork '09 Numbers Template" },
            { "NRW", "Nikon RAW (2) (TIFF-based)" },
            { "NUMBERS", "Apple iWork '09 Numbers spreadsheet" },
            { "O", "Unix compiled code Object" },
            { "ODB", "Open Document Database/Chart/Formula/Graphics/Image/Presentation/Spreadsheet/Text (ZIP/XML-based)" },
            { "ODC", "Open Document Database/Chart/Formula/Graphics/Image/Presentation/Spreadsheet/Text (ZIP/XML-based)" },
            { "ODF", "Open Document Database/Chart/Formula/Graphics/Image/Presentation/Spreadsheet/Text (ZIP/XML-based)" },
            { "ODG", "Open Document Database/Chart/Formula/Graphics/Image/Presentation/Spreadsheet/Text (ZIP/XML-based)" },
            { "ODI", "Open Document Database/Chart/Formula/Graphics/Image/Presentation/Spreadsheet/Text (ZIP/XML-based)" },
            { "ODP", "Open Document Database/Chart/Formula/Graphics/Image/Presentation/Spreadsheet/Text (ZIP/XML-based)" },
            { "ODS", "Open Document Database/Chart/Formula/Graphics/Image/Presentation/Spreadsheet/Text (ZIP/XML-based)" },
            { "ODT", "Open Document Database/Chart/Formula/Graphics/Image/Presentation/Spreadsheet/Text (ZIP/XML-based)" },
            { "OFR", "OptimFROG audio (RIFF-based)" },
            { "OGG", "Ogg bitstream container" },
            { "OGV", "Ogg bitstream container" },
            { "ONP", "ON1 Presets" },
            { "OPUS", "Ogg Opus audio" },
            { "ORF", "Olympus RAW Format (TIFF-based)" },
            { "ORI", "Olympus RAW Format (TIFF-based)" },
            { "OTF", "Open Type Font" },
            { "PAC", "Lossless Predictive Audio Compression (RIFF-based)" },
            { "PAGES", "Apple iWork '09 Pages document" },
            { "PCD", "Kodak Photo CD Image Pac" },
            { "PCX", "PC Paintbrush" },
            { "PDB", "Palm Database" },
            { "PRC", "Palm Database" },
            { "PDF", "Adobe Portable Document Format" },
            { "PEF", "Pentax (RAW) Electronic Format (TIFF-based)" },
            { "PFA", "PostScript Font ASCII/Binary" },
            { "PFB", "PostScript Font ASCII/Binary" },
            { "PFM", "Printer Font Metrics / Portable FloatMap" },
            { "PGF", "Progressive Graphics File" },
            { "PICT", "Apple Picture file" },
            { "PCT", "Apple Picture file" },
            { "PLIST", "Apple Property List (binary and XML formats)" },
            { "PMP", "Sony DSC-F1 Cyber-Shot image" },
            { "PNG", "Portable/JPEG/Multiple-image Network Graphics" },
            { "JNG", "Portable/JPEG/Multiple-image Network Graphics" },
            { "MNG", "Portable/JPEG/Multiple-image Network Graphics" },
            { "PPM", "Portable Pixel/Bit/Gray Map" },
            { "PBM", "Portable Pixel/Bit/Gray Map" },
            { "PGM", "Portable Pixel/Bit/Gray Map" },
            { "PPT", "PowerPoint Presentation/Slideshow/Template (FPX-like)" },
            { "PPS", "PowerPoint Presentation/Slideshow/Template (FPX-like)" },
            { "POT", "PowerPoint Presentation/Slideshow/Template (FPX-like)" },
            { "POTX", "Office Open XML Presentation Template [Macro-enabled]" },
            { "POTM", "Office Open XML Presentation Template [Macro-enabled]" },
            { "PPAX", "Office Open XML Presentation Addin [Macro-enabled]" },
            { "PPAM", "Office Open XML Presentation Addin [Macro-enabled]" },
            { "PPSX", "Office Open XML Presentation Slideshow [Macro-enabled]" },
            { "PPSM", "Office Open XML Presentation Slideshow [Macro-enabled]" },
            { "PPTX", "Office Open XML Presentation [Macro-enabled]" },
            { "PPTM", "Office Open XML Presentation [Macro-enabled]" },
            { "PSD", "PhotoShop Document / Large Document / Template" },
            { "PSB", "PhotoShop Document / Large Document / Template" },
            { "PSDT", "PhotoShop Document / Large Document / Template" },
            { "PSP", "Paint Shop Pro" },
            { "PSPIMAGE", "Paint Shop Pro" },
            { "QTIF", "QuickTime Image File" },
            { "QTI", "QuickTime Image File" },
            { "QIF", "QuickTime Image File" },
            { "R3D", "Redcode RAW video" },
            { "RA", "Real Audio" },
            { "RAF", "FujiFilm RAW Format" },
            { "RAM", "Real Audio/Plug-in Metafile" },
            { "RPM", "Real Audio/Plug-in Metafile" },
            { "RAR", "RAR Archive" },
            { "RAW", "Kyocera Contax N Digital RAW / Panasonic RAW (TIFF-based)" },
            { "RIFF", "Resource Interchange File Format" },
            { "RIF", "Resource Interchange File Format" },
            { "RM", "Real Media/Video [Variable Bitrate]" },
            { "RV", "Real Media/Video [Variable Bitrate]" },
            { "RMVB", "Real Media/Video [Variable Bitrate]" },
            { "RSRC", "Mac OS Resource" },
            { "RTF", "Rich Text Format" },
            { "RW2", "Panasonic RAW 2 (TIFF-based)" },
            { "RWL", "Leica RAW (TIFF-based)" },
            { "RWZ", "Rawzor compressed image" },
            { "SEQ", "FLIR Systems image Sequence" },
            { "SKETCH", "Sketch design file" },
            { "SO", "Unix ELF executable and Shared Object files" },
            { "SR2", "Sony RAW 2 (TIFF-based)" },
            { "SRF", "Sony RAW Format (TIFF-based)" },
            { "SRW", "Samsung RAW format (TIFF-based)" },
            { "SVG", "Scalable Vector Graphics (XML-based)" },
            { "SWF", "Shockwave Flash" },
            { "THM", "Thumbnail image (JPEG)" },
            { "THMX", "Office Open XML Theme" },
            { "TIFF", "Tagged Image File Format" },
            { "TIF", "Tagged Image File Format" },
            { "TTF", "True Type Font/Collection" },
            { "TTC", "True Type Font/Collection" },
            { "TORRENT", "BitTorrent description file" },
            { "TXT", "Text files" },
            { "VCF", "Virtual Card" },
            { "VCARD", "Virtual Card" },
            { "VOB", "Video Object (MPEG-based)" },
            { "VRD", "Canon DPP Recipe Data" },
            { "VSD", "Microsoft Visio Drawing (FPX-like)" },
            { "WAV", "Windows digital audio WAVeform (RIFF-based)" },
            { "WEBM", "Google Web Movie (Matroska-based)" },
            { "WEBP", "Google Web Picture (RIFF-based)" },
            { "WMA", "Windows Media Audio/Video (ASF-based)" },
            { "WMV", "Windows Media Audio/Video (ASF-based)" },
            { "WTV", "Windows recorded TV show" },
            { "WV", "WavePack lossless audio (RIFF-based)" },
            { "X3F", "Sigma/Foveon RAW" },
            { "XCF", "GIMP native image format" },
            { "XLS", "Microsoft Excel Spreadsheet/Template (FPX-like)" },
            { "XLT", "Microsoft Excel Spreadsheet/Template (FPX-like)" },
            { "XLSX", "Office Open XML Spreadsheet [Macro-enabled/Binary]" },
            { "XLSM", "Office Open XML Spreadsheet [Macro-enabled/Binary]" },
            { "XLSB", "Office Open XML Spreadsheet [Macro-enabled/Binary]" },
            { "XLTX", "Office Open XML Spreadsheet Template [Macro-enabled]" },
            { "XLTM", "Office Open XML Spreadsheet Template [Macro-enabled]" },
            { "XMP", "Extensible Metadata Platform sidecar file" },
            { "ZIP", "ZIP archive" },
        };

        public static IReadOnlyDictionary<string, string> Writeable { get; } = new Dictionary<string, string>
        {
            { "360", "GoPro 360 video (QuickTime-based)" },
            { "3G2", "3rd Gen. Partnership Project 2 a/v (QuickTime-based)" },
            { "3GP2", "3rd Gen. Partnership Project 2 a/v (QuickTime-based)" },
            { "3GP", "3rd Gen. Partnership Project a/v (QuickTime-based)" },
            { "3GPP", "3rd Gen. Partnership Project a/v (QuickTime-based)" },
            { "AAX", "Audible Enhanced Audiobook (QuickTime-based)" },
            { "AI", "Adobe Illustrator [Template] (PS or PDF)" },
            { "AIT", "Adobe Illustrator [Template] (PS or PDF)" },
            { "ARQ", "Sony Alpha Pixel-Shift RAW (TIFF-based)" },
            { "ARW", "Sony Alpha RAW (TIFF-based)" },
            { "AVIF", "AV1 Image File Format (QuickTime-based)" },
            { "CR2", "Canon RAW 2 (TIFF-based) (CR2 spec)" },
            { "CR3", "Canon RAW 3 (QuickTime-based) (CR3 spec)" },
            { "CRM", "Canon RAW Movie (QuickTime-based)" },
            { "CRW", "Canon RAW Camera Image File Format (CRW spec)" },
            { "CIFF", "Canon RAW Camera Image File Format (CRW spec)" },
            { "CS1", "Sinar CaptureShop 1-shot RAW (PSD-based)" },
            { "DCP", "DNG Camera Profile (DNG-like)" },
            { "DNG", "Digital Negative (TIFF-based)" },
            { "DR4", "Canon DPP version 4 Recipe" },
            { "DVB", "Digital Video Broadcasting (QuickTime-based)" },
            { "EPS", "[Encapsulated] PostScript Format" },
            { "EPSF", "[Encapsulated] PostScript Format" },
            { "PS", "[Encapsulated] PostScript Format" },
            { "ERF", "Epson RAW Format (TIFF-based)" },
            { "EXIF", "Exchangeable Image File Format metadata (TIFF-based)" },
            { "EXV", "Exiv2 metadata file (JPEG-based)" },
            { "F4A", "Adobe Flash Player 9+ Audio/Video (QuickTime-based)" },
            { "F4B", "Adobe Flash Player 9+ Audio/Video (QuickTime-based)" },
            { "F4P", "Adobe Flash Player 9+ Audio/Video (QuickTime-based)" },
            { "F4V", "Adobe Flash Player 9+ Audio/Video (QuickTime-based)" },
            { "FFF", "Hasselblad Flexible File Format (TIFF-based)" },
            { "FLIF", "Free Lossless Image Format" },
            { "GIF", "Compuserve Graphics Interchange Format" },
            { "GPR", "GoPro RAW (DNG-based)" },
            { "HDP", "Windows HD Photo / Media Photo / JPEG XR (TIFF-based)" },
            { "WDP", "Windows HD Photo / Media Photo / JPEG XR (TIFF-based)" },
            { "JXR", "Windows HD Photo / Media Photo / JPEG XR (TIFF-based)" },
            { "HEIC", "High Efficiency Image Format (QuickTime-based)" },
            { "HEIF", "High Efficiency Image Format (QuickTime-based)" },
            { "HIF", "High Efficiency Image Format (QuickTime-based)" },
            { "ICC", "International Color Consortium color profile" },
            { "ICM", "International Color Consortium color profile" },
            { "IIQ", "Phase One Intelligent Image Quality RAW (TIFF-based)" },
            { "IND", "Adobe InDesign Document/Template" },
            { "INDD", "Adobe InDesign Document/Template" },
            { "INDT", "Adobe InDesign Document/Template" },
            { "INSP", "Insta360 Picture (JPEG-based)" },
            { "JP2", "JPEG 2000 image [Compound/Extended]" },
            { "JPF", "JPEG 2000 image [Compound/Extended]" },
            { "JPM", "JPEG 2000 image [Compound/Extended]" },
            { "JPX", "JPEG 2000 image [Compound/Extended]" },
            { "JPEG", "Joint Photographic Experts Group image" },
            { "JPG", "Joint Photographic Experts Group image" },
            { "JPE", "Joint Photographic Experts Group image" },
            { "JXL", "JPEG XL (codestream and ISO BMFF)" },
            { "LRV", "Low-Resolution Video (QuickTime-based)" },
            { "M4A", "MPEG-4 Audio/Video (QuickTime-based)" },
            { "M4B", "MPEG-4 Audio/Video (QuickTime-based)" },
            { "M4P", "MPEG-4 Audio/Video (QuickTime-based)" },
            { "M4V", "MPEG-4 Audio/Video (QuickTime-based)" },
            { "MEF", "Mamiya (RAW) Electronic Format (TIFF-based)" },
            { "MIE", "Meta Information Encapsulation (MIE specification)" },
            { "MOS", "Creo Leaf Mosaic (TIFF-based)" },
            { "MOV", "Apple QuickTime Movie" },
            { "QT", "Apple QuickTime Movie" },
            { "MP4", "Motion Picture Experts Group version 4 (QuickTime-based)" },
            { "MPO", "Extended Multi-Picture format (JPEG with MPF extensions)" },
            { "MQV", "Sony Mobile QuickTime Video" },
            { "MRW", "Minolta RAW" },
            { "MRC", "Medical Research Council" },
            { "MXF", "Material Exchange Format" },
            { "NEF", "Nikon (RAW) Electronic Format (TIFF-based)" },
            { "NKSC", "Nikon Sidecar (XMP-based)" },
            { "NRW", "Nikon RAW (2) (TIFF-based)" },
            { "ORF", "Olympus RAW Format (TIFF-based)" },
            { "ORI", "Olympus RAW Format (TIFF-based)" },
            { "PDF", "Adobe Portable Document Format" },
            { "PEF", "Pentax (RAW) Electronic Format (TIFF-based)" },
            { "PNG", "Portable/JPEG/Multiple-image Network Graphics" },
            { "JNG", "Portable/JPEG/Multiple-image Network Graphics" },
            { "MNG", "Portable/JPEG/Multiple-image Network Graphics" },
            { "PPM", "Portable Pixel/Bit/Gray Map" },
            { "PBM", "Portable Pixel/Bit/Gray Map" },
            { "PGM", "Portable Pixel/Bit/Gray Map" },
            { "PSD", "PhotoShop Document / Large Document / Template" },
            { "PSB", "PhotoShop Document / Large Document / Template" },
            { "PSDT", "PhotoShop Document / Large Document / Template" },
            { "QTIF", "QuickTime Image File" },
            { "QTI", "QuickTime Image File" },
            { "QIF", "QuickTime Image File" },
            { "RAF", "FujiFilm RAW Format" },
            { "RAW", "Panasonic RAW (TIFF-based)" },
            { "RW2", "Panasonic RAW 2 (TIFF-based)" },
            { "RWL", "Leica RAW (TIFF-based)" },
            { "SR2", "Sony RAW 2 (TIFF-based)" },
            { "SRW", "Samsung RAW format (TIFF-based)" },
            { "THM", "Thumbnail image (JPEG)" },
            { "TIFF", "Tagged Image File Format" },
            { "TIF", "Tagged Image File Format" },
            { "VRD", "Canon DPP Recipe Data" },
            { "X3F", "Sigma/Foveon RAW" },
            { "XMP", "Extensible Metadata Platform sidecar file" },
        };
    }
}
