//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FileManager.Resources {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "17.3.0.0")]
    internal sealed partial class GeneralPageSettings : global::System.Configuration.ApplicationSettingsBase {
        
        private static GeneralPageSettings defaultInstance = ((GeneralPageSettings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new GeneralPageSettings())));
        
        public static GeneralPageSettings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool CardExpanderMove {
            get {
                return ((bool)(this["CardExpanderMove"]));
            }
            set {
                this["CardExpanderMove"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool CardExpanderDelete {
            get {
                return ((bool)(this["CardExpanderDelete"]));
            }
            set {
                this["CardExpanderDelete"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool CardExpanderRename {
            get {
                return ((bool)(this["CardExpanderRename"]));
            }
            set {
                this["CardExpanderRename"] = value;
            }
        }
    }
}
